
export const GEMINI_API_KEY = "AIzaSyD9piPuyDV_J8-quGj3yZRq0r1se54UYOQ";
export const SUPABASE_URL = "https://pzbhluqbhpwcocqfmrcp.supabase.co";
export const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6YmhsdXFiaHB3Y29jcWZtcmNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ2NjUxNzgsImV4cCI6MjA4MDI0MTE3OH0.vswx9pFnia38Zp0_6CBVtTpecV1d6ZdkWk_MgLnQrnA";
