
export const ANIMATION_DURATIONS = {
  SUCCESS_FEEDBACK: 800,
  SHAKE_FEEDBACK: 500,
  MODAL_TRANSITION: 300,
  INBOX_ZERO_CELEBRATION: 2500,
  VIEW_TRANSITION: 300,
};

export const INTERACTION = {
  DRAG_LONG_PRESS_MS: 250,
  DRAG_DISTANCE_CANCEL_PX: 10,
  SWIPE_THRESHOLD_PX: 50,
  GESTURE_LOCK_THRESHOLD_PX: 5,
  VIBRATION: {
    SOFT: 20,
    MEDIUM: 30,
    SUCCESS: 50,
    HARD: [40, 30, 40],
    AI_AUTO_SORT: [20, 30, 20],
  }
};

export const LAYOUT = {
  SWIPE_ACTION_WIDTH_PX: 80,
  BOTTOM_NAV_RESERVE_PX: 110,
};
